# rta-svc

@apiurl = http://localhost:8090
# @apiurl = https://rta-svc.beta.zerodhafundhouse.com
# @apiurl = https://rta-svc.prod.zerodhafundhouse.com
@version = v2

###
# @name Health check
GET {{apiurl}}/health

###
# @name Get onboarding
GET {{apiurl}}/{{version}}/api/user/v1/onboarding?emailId=umang5@gmail.com

###
# @name Post onboarding
POST {{apiurl}}/{{version}}/api/user/v1/onboarding
Content-Type: application/json

{
    "emailId": "umang5@gmail.com",
    "name": "Umang Tiwary",
    "avatarUrl": "www.google.com"
}

###
# @name Init form
POST {{apiurl}}/{{version}}/api/form/v1/init
Content-Type: application/json

{
    "companyId": "12321-213123-123213"
}

###
# @name Update form
POST {{apiurl}}/{{version}}/api/form/v1/update
Content-Type: application/json

{
    "formId": "T4YTG5KA88IEL4PB4TJVR",
    "companyId": "12321-213123-123213",
    "businessMetaData": { "name": "smallcase" },
    "formName": "Test form",
    "googlePageId": "GPID-1",
    "aboutForm": "This is feedback form our small restaurant in Indiranagar, Bangalore",
    "formContent": { "a": "b" },
    "formTheme": { "colorCode": "#ffff" }
}

###
# @name Get form
GET {{apiurl}}/{{version}}/api/form/v1/getForm?formId=0ZNXPK8IDJD2U7ZLYI0DF

###
# @name Create Lead
POST {{apiurl}}/{{version}}/api/lead/v1/createLead
Content-Type: application/json

{
    "mobileNumber": "9089898897"
}

###
# @name Update Lead
POST {{apiurl}}/{{version}}/api/lead/v1/updateLead
Content-Type: application/json

{
    "mobileNumber": "9089898897",
    "businessName": "Umang Shoe Store",
    "businessPlaceId": "hjashdajdh144787187XD",
    "businessAddress": "Old Airport Road, Bengaluru",
    "userName": "Umang Tiwary",
    "emailId": "umang@gmail.com"
}

###
# @name Create Company
POST {{apiurl}}/{{version}}/api/company/v1/createCompany
Content-Type: application/json

{
    "userId": "8bda2548-2c1c-400c-bb9a-b76952411ed3",
    "companyName": "Umang Shoe Stores ASDA"
}

###
# @name Get Company
GET {{apiurl}}/{{version}}/api/company/v1/getCompany?companyId=202f68a-f242-4f93-a6ea-7c9126fd67b3

###
# @name Save form response
POST {{apiurl}}/{{version}}/api/signup/v2/response
Content-Type: application/json

{
    "responses": {
        "ABC": {
            "isUserText": true,
            "questionTitle": "How did you like the service?",
            "responses": ["Food is amazing", "DJ was top-notch"]
        },
        "ABD": {
            "isUserText": false,
            "questionTitle": "How much rating would you like to give?",
            "rating": "4.5"
        }
    },
    "formId": "T4YTG5KA88IEL4PB4TJVR",
    "companyId": "ABC",
    "queryParams": {}
}

###
# @name Get generated review
GET {{apiurl}}/{{version}}/api/signup/v1/review?responseId=ed7e8d0f-9145-4bf0-b9e1-bd51849a7989
