# rta-svc

@apiurl = http://localhost:8090
# @apiurl = https://rta-svc.beta.zerodhafundhouse.com
# @apiurl = https://rta-svc.prod.zerodhafundhouse.com
@version = v2

###
# @name Health check
GET {{apiurl}}/health

###
# @name Get onboarding
GET {{apiurl}}/{{version}}/api/user/v1/onboarding?emailId=umang5@gmail.com

###
# @name Post onboarding
POST {{apiurl}}/{{version}}/api/user/v1/onboarding
Content-Type: application/json

{
    "emailId": "umang5@gmail.com",
    "name": "Umang Tiwary",
    "avatarUrl": "www.google.com"
}

###
# @name Init form
POST {{apiurl}}/{{version}}/api/form/v1/init
Content-Type: application/json

{
    "companyId": "12321-213123-123213"
}

###
# @name Update form
POST {{apiurl}}/{{version}}/api/form/v1/update
Content-Type: application/json

{
    "formId": "VN7FDGJ682QDAJ7B0W385",
    "companyId": "12321-213123-123213",
    "businessMetaData": { "name": "smallcase" },
    "formName": "Test form",
    "googlePageId": "GPID-1",
    "aboutForm": { "description": "Test form description" },
    "formContent": { "a": "b" },
    "formTheme": { "colorCode": "#ffff" }
}

###
# @name Get form
GET {{apiurl}}/{{version}}/api/form/v1/getForm?formId=0ZNXPK8IDJD2U7ZLYI0DF


###
# @name Create Lead
POST {{apiurl}}/{{version}}/api/lead/v1/createLead
Content-Type: application/json

{
    "mobileNumber": "9089898897"
}


###
# @name Update Lead
POST {{apiurl}}/{{version}}/api/lead/v1/updateLead
Content-Type: application/json

{
    "mobileNumber": "9089898897",
    "businessName": "Umang Shoe Store",
    "businessPlaceId": "hjashdajdh144787187XD",
    "businessAddress": "Old Airport Road, Bengaluru",
    "userName": "Umang Tiwary",
    "emailId": "umang@gmail.com"
}


###


# @name Create Company
POST {{apiurl}}/{{version}}/api/company/v1/createCompany
Content-Type: application/json

{
    "userId": "8bda2548-2c1c-400c-bb9a-b76952411ed3",
    "companyName": "Umang Shoe Stores ASDA"
}

###
# @name Get Company
GET {{apiurl}}/{{version}}/api/company/v1/getCompany?companyId=202f68a-f242-4f93-a6ea-7c9126fd67b3