server:
  port: 3001
spring:
  datasource:
    url: jdbc:mysql://bloom-mysql-do-user-14415900-0.b.db.ondigitalocean.com:25060/user_db?ssl-mode=REQUIRED
    username: doadmin
    password: AVNS_nQ4CgD2pSHqu6okWkSz
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 60000
      connection-timeout: 2000
      maximum-pool-size: 35
      minimum-idle: 1
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    openInView: false
    show_sql: false
    generate-ddl: true
